import =[
    "~/.config/alacritty/catppuccin-frappe.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14
normal = { family = "MonoLisa Nerd Font", style = "Light Regular" }
italic = { style = "Light Italic" }
bold = { style = "SemiBold Regular" }
bold_italic = { style = "SemiBold Italic" }

[window]
resize_increments = true
# decorations = "Buttonless"
dynamic_title = false
option_as_alt = "OnlyLeft"
position = { x = 0, y = 2000 }
dimensions = { columns = 160, lines = 50 }

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
